### ISSUE TITLE
Cache poetry deps in Github Actions in order to speed up builds

### ISSUE THREAD

**Issue by atapin** [ourzora/offchain#109]
This can be done by modifying setup python step:

```yaml
- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.9'
    cache: poetry
    cache-dependency-path: poetry.lock
```
